name: Build CMake

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'cmake/**'

env:
  Registry: registry.cn-hangzhou.aliyuncs.com/tianlongxiang51/cmake

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v1 
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./cmake/.
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.Registry }}:latest
            ${{ env.Registry }}:${{ github.sha }}